### ISSUE TITLE
Error in entering unreal

### ISSUE THREAD

**Issue by h27han** [ue4plugins/VlcMedia#14]
I cloned the repository under engine/plugins/medias but the error message showed up:
Plugin 'vlcMedia' fails to load because module 'vlcMedia' could not be found. Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.
I have 4.11 preview version

**Comment by gmpreussner** [comment]
Did you compile the project?

**Comment by h27han** [comment]
It seems like I may have messed up the installation step, thank you for answering.
On the side note, is the audio working on vlcMedia now?
Also, My initial try was to use media framework embedded but it seems like it does not support streaming link we got from youtube, for example:
https://r13---sn-tt17rn76.googlevideo.com/videoplayback?pl=16&mime=video%2Fmp4&expire=1452719538&ip=99.236.206.226&key=cms1&dur=170.388&ratebypass=yes&source=youtube&lmt=1433981700634915&requiressl=yes&ipbits=0&signature=585954C2CD13A24A2114F7C15CF9B6F772CFEEFB.0D800C21E312F0B454A78C61AB9219B65D493B36&fexp=9406985%2C9416126%2C9420452%2C9422596%2C9423662%2C9427016&sver=3&id=o-APYdpFS8pD_5tbyiHIRgROiSqctw0KGxLxXdlVQdFUaq&sparams=dur,expire,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,upn&upn=x4B3Mr8bHPU&itag=22&redirect_counter=1&req_id=cdbe031be98ca3ee&cms_redirect=yes&mm=30&mn=sn-tt17rn76&ms=nxu&mt=1452699354&mv=m
which does not end in any extension. Any thoughts on that?
Thanks

**Comment by gmpreussner** [comment]
Audio is not supported yet. I might be able to work on it this week or next week.

YouTube is not supported and will not be supported via VlcMedia. I have another project for that, but didn't make any progress yet due to lack of time (https://github.com/ue4plugins/YtMedia). YouTube support can only be accomplished via an integrated web browser widget, because there exists no library that can stream YouTube video natively.
