### ISSUE TITLE
Vlc Plugin Doesn't work in packaged project

### ISSUE THREAD

**Issue by thesissrl** [ue4plugins/VlcMedia#28]
Hi, I tried to package (shipping win64) a project with vlc plugin enabled. In the editor everithing works fine but when I package the progect and execute the exe file of the project the vlc pluging doesn't work anymore. No error is detected but the videos aren't showing.
How can i solve the problem?

**Comment by Deams51** [comment]
Hey :) 
Same here. 
In the logs, concerning VLC there seems to be only one issue: 
`[2016.11.17-14.47.04:129][  0]LogVlcMedia:Warning: Failed to create VLC instance ((null))`

**Comment by thesissrl** [comment]
Hi!
Same behaviour for me:
First:
`1. LogPluginManager: Loaded Plugin VlcMedia, From C:/Users/domen/Desktop/360/WindowsNoEditor/Engine/Plugins/Media/VlcMedia-4.14/VlcMedia.uplugin`

But Then:
`[2016.11.17-15.18.58:289][  0]LogVlcMedia:Warning: Failed to create VLC instance (`(null))

Hope that someone could help!

**Comment by Deams51** [comment]
Alright seems the issue is due to the vlc "plugins" folder not being copied during packaging in the VLC plugin folder.
Might be unrelated, but it seems that even by setting the player name like this: 
`MediaPlayer->DesiredPlayerName = TEXT("VlcMedia");`
UE is using the Wmf player in the packeged game while using Vlc in editor.

**Comment by thesissrl** [comment]
Ok Thanks, Manually copying the VlcMedia files in Plugins folder of packaged game solves the problem!
