### ISSUE TITLE
High latency on streaming RTSP

### ISSUE THREAD

**Issue by araratm** [ue4plugins/VlcMedia#31]
I'm using vlc player to stream rtsp videos, but the latency is so big, it updates frames every second and sometimes it takes a little bit less. 

In general it has high latency rate. 
Can anybody help me? Is there an option for that? Or is there specific video sizes?

**Comment by gmpreussner** [comment]
@araratm could it be the server or maybe your internet connection? I've streamed RTSP from various internet sources without problems. Sometimes it takes a while to connect and buffer, but once it plays, there are no frame rate issues.

**Comment by JuanAzassino** [comment]
Seems this issue is related to mine. I am using a pure rtsp:// feed, Camera feed only updates every 10 seconds or so in the unreal engine client, I have to first play the video on the Media Player Class and then play my scene to see the feed else it does not work. And at times crashes the engine when tried to play consecutively. Is there a setting or something I may be missing?

**Comment by gmpreussner** [comment]
When are you initiating playback?

Make sure you either check the 'Play On Open' checkbox in the MediaPlayer, or otherwise listen to the OnMediaOpened event in your Blueprint and call Play from there. Do not call Play right after Open as the media source will take some time to connect and buffer. Play will only work once the media finished opening successfully.

If you keep having problem, please send me your RTSP stream URL. If you want to keep it private, you can email it to me. Thanks!
